name: Update rust-toolchain

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 1" # 3:30 on Monday

jobs:
  update-rust-toolchain:
    name: Update Rust toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@1536e372d5f433385f11b5b133b23a9833c510ce # v2.86.0

      - name: Update rust version inside of rust-toolchain file
        id: update_rust_toolchain
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: |-
          updatecli apply --config ./updatecli/updatecli.d/update-rust-toolchain.yaml \
                    --values updatecli/values.yaml
